<a href="https://colab.research.google.com/github/saba-tabassum-1902/Python_Notes/blob/main/SABA_PANDAS_NOTES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## INTRODUCTION TO PANDAS##

In [ ]:
#what is pandas?
#open source library, That works mainly with the labelled data
#why we are using the pandas?
#fast, high performence, and productive , and easy to load and read the data
#flexible reshaping of the data and pivoting the data, data visualisation and grou by functionality
#time series analysis

In [ ]:
#what is the function of pandas?
#Analysing the data, cleaning, exploring, and manipulating the data

In [ ]:
#what is data cleaning?
#delete irrelevent data, empty or null values , correction of data types , fill null values

Installation of pandas

In [ ]:
!pip install pandas

In [ ]:
#import the module
import pandas as pd

In [ ]:
#How many data structures do we have in pandas?
#There are 3types
#1.SERIES:- series are nothing but 1D labelled Array's
#How can we build a series?

In [ ]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]

In [ ]:
sr = pd.Series(a)
print(sr)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#How can we change the labelles?
sr = pd.Series(a,index=['a','b','c','d'])
print(sr)

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
#create a series from the dictionary?
d = {
    "name":"medha",
    "course": "DS",
    "Duration": "4months"
}
sr = pd.Series(d)
print(sr)
#How can we represent a series in pandas
print(type(sr))
#ans) <class 'pandas.core.series.Series'>

name          medha
course           DS
Duration    4months
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
#create a series from tuple of fruits and give the labels as 'a','b','c','d
#create a series from list of fruits and give the labels as 'a','b','c','d

In [ ]:
#canwe create aseries from the set---> No
a = {1,2,3,4,5}
sr = pd.Series(a)
print(sr)

In [ ]:
#2D-Data-Frame:
#Dataframe is 2d-size, Heterogenous data with labelled axis(rows and columns), mutable
#columns also known as features, variables, fields,dimesions, attributes
#rows also known as records,values, index

In [ ]:
#what is the application of dataframe?
#works on data sets
#analysis
#dropping
#processing
#clening
#join the multiple data
#create excel,json and finary files..etc
#compute mathematical and statistical operations
#use group by function

In [ ]:
#create a dataframe from list
l = [1,2,3,4,5,6,7]
df = pd.DataFrame(l)
print(df)

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7

In [ ]:
#create a dataframe from the set of fruits or numbers
s1 = {'apple','banana','orange','pineapple','grapes'}
df = pd.DataFrame(s1,index = ['a','b','c','d','e'])
print(df)

           0
a  pineapple
b     grapes
c      apple
d     banana
e     orange

##importing and exporting the data ##

In [ ]:
#1.csv--> comma, seprate, values
#Read the csv file by using the pandas
import pandas as pd

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')
#package-->modules<--code libraries
#convert the above data in to excel format
df.to_excel('sample.xlsx')

In [ ]:
#read the df
df.head(10)

In [ ]:
#read the excel file
df2 = pd.read_excel('/content/sample.xlsx')
df2.head()

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,0,-114.31,34.19,15,5612,1283,1015,472,1.4936,66900
1,1,-114.47,34.40,19,7650,1901,1129,463,1.8200,80100
2,2,-114.56,33.69,17,720,174,333,117,1.6509,85700
3,3,-114.57,33.64,14,1501,337,515,226,3.1917,73400
4,4,-114.57,33.57,20,1454,326,624,262,1.9250,65500

In [ ]:
#convert the excel file into json format.
df2.to_json('sample.json')

In [ ]:
#read the json data
df3 = pd.read_json('/content/sample.json')
df3.head()

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,0,-114.31,34.19,15,5612,1283,1015,472,1.4936,66900
1,1,-114.47,34.40,19,7650,1901,1129,463,1.8200,80100
2,2,-114.56,33.69,17,720,174,333,117,1.6509,85700
3,3,-114.57,33.64,14,1501,337,515,226,3.1917,73400
4,4,-114.57,33.57,20,1454,326,624,262,1.9250,65500

**Data Frame Functions**

In [ ]:
#step1:-read the data
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [ ]:
#step2:- check the size and index of the df
df.size  #size--> no of rows * no of columns
#index gives the range of index from start to end along with the step
df.index

RangeIndex(start=0, stop=17000, step=1)

In [ ]:
#read the columns of your data
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
#check the number of rows and columns
df.shape

(17000, 9)

In [ ]:
#get the overall information of the dataframe?
df.info()

This data is having 17000 rows and 9 columns

There no null values

for all the columns the data type is  float

In [ ]:
#print the data types for above dataframe
df.dtypes

In [ ]:
#How to describe  overall data according to staistics?
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
#print the last 5 rows for above df
df.tail()  #by default df.tail can print the last 5 rows

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
#check the null values
df.isnull()  #returns the boolean expression of null values present or not

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
16995,False,False,False,False,False,False,False,False,False
16996,False,False,False,False,False,False,False,False,False
16997,False,False,False,False,False,False,False,False,False
16998,False,False,False,False,False,False,False,False,False
16999,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
#1.pd.Series(name,index=['a','b'])
#2.pd.DataFrame(name, index)
#3.pd.read_csv("file path")--> read the csv
#4.df.head() --> by default it read the 1st 5 rows
#5.df.shape---> read the total number of rows and columns
#6.df.index--> returns the range of indexes from start to end along with step
#7.df.columns--> read the columns of the data
#8.df.info()--> overall information of df
#9.df.describe()--> descriptive stats of dataframe
#10.df.tail--->  by default it reads last 5 rows of the df
#11.df.isnull().sum()--> gives the totral null values in the dataframe

##03-06-2025##

##Accesing the Data Frame##

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv ("/content/sample_data/california_housing_train.csv")
#read 1st 5 rows of the df
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
#print the column names
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
#read and access the column 'total_bedrooms'
df['total_bedrooms']

0        1283.0
1        1901.0
2         174.0
3         337.0
4         326.0
          ...
16995     394.0
16996     528.0
16997     531.0
16998     552.0
16999     300.0
Name: total_bedrooms, Length: 17000, dtype: float64

In [ ]:
#read the first 5 rows
df['total_bedrooms'].head()
df['total_bedrooms'].tail()

16995    394.0
16996    528.0
16997    531.0
16998    552.0
16999    300.0
Name: total_bedrooms, dtype: float64

In [ ]:
df['total_bedrooms'].head()
#print the 1st row value of column 'total_bedrooms'
df['total_bedrooms'][0]

np.float64(1283.0)

In [ ]:
#print the indexes -----> 1545,12455,6500
df['total_bedrooms'][100:200]

100     307.0
101     177.0
102     187.0
103     317.0
104     244.0
        ...
195    1238.0
196     348.0
197    3479.0
198    2405.0
199    2460.0
Name: total_bedrooms, Length: 100, dtype: float64

In [ ]:
df['total_bedrooms'][1545]
df['total_bedrooms'][12455]
df['total_bedrooms'][6500]

np.float64(424.0)

In [ ]:
#how can we access the multiple column ? 'total_bedrooms','total_bedroom','population'
df[['total_rooms','total_bedrooms', 'population']].head()

   total_rooms  total_bedrooms  population
0       5612.0          1283.0      1015.0
1       7650.0          1901.0      1129.0
2        720.0           174.0       333.0
3       1501.0           337.0       515.0
4       1454.0           326.0       624.0

loc() is used to locate rows

In [ ]:
#df.loc[start:end:step]
#print the entire forst row of my dataframe
df.loc[0]
#print the valuesrows from 100 to 105
#df.loc[start:end]
df.loc[100:106]
#read the rows with even and odd indexex up to the 100th row
df.loc[0:100:2]#even index rows
df.loc[1:100:2]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0
11,-114.60,33.60,21.0,1988.0,483.0,1182.0,437.0,1.6250,62000.0
13,-114.61,34.83,31.0,2478.0,464.0,1346.0,479.0,3.2120,70400.0
15,-114.65,34.89,17.0,2556.0,587.0,1005.0,401.0,1.6991,69100.0
17,-114.65,32.79,21.0,44.0,33.0,64.0,27.0,0.8571,25000.0
19,-114.67,33.92,17.0,97.0,24.0,29.0,15.0,1.2656,27500.0
21,-114.73,33.43,24.0,796.0,243.0,227.0,139.0,0.8964,59200.0
23,-114.98,33.82,15.0,644.0,129.0,137.0,52.0,3.2097,71300.0
25,-115.32,32.82,34.0,591.0,139.0,327.0,89.0,3.6528,100000.0
27,-115.37,32.82,14.0,1276.0,270.0,867.0,261.0,1.9375,80900.0
29,-115.37,32.81,23.0,1458.0,294.0,866.0,275.0,2.3594,74300.0
31,-115.38,32.81,35.0,1263.0,262.0,950.0,241.0,1.8958,67500.0
33,-115.40,32.86,19.0,1087.0,171.0,649.0,173.0,3.3182,113800.0
35,-115.41,32.99,29.0,1141.0,220.0,684.0,194.0,3.4038,107800.0
37,-115.48,32.80,21.0,1260.0,246.0,805.0,239.0,2.6172,88500.0
39,-115.49,32.87,19.0,541.0,104.0,457.0,106.0,3.3583,102800.0
41,-115.49,32.67,29.0,1523.0,440.0,1302.0,393.0,1.1311,84700.0
43,-115.50,32.75,13.0,330.0,72.0,822.0,64.0,3.4107,142500.0
45,-115.50,32.67,35.0,2159.0,492.0,1694.0,475.0,2.1776,75500.0
47,-115.51,33.12,21.0,1024.0,218.0,890.0,232.0,2.1010,46700.0
49,-115.51,32.68,11.0,2872.0,610.0,2644.0,581.0,2.6250,72700.0
51,-115.52,33.13,18.0,1109.0,283.0,1006.0,253.0,2.1630,53400.0
53,-115.52,32.98,32.0,1615.0,382.0,1307.0,345.0,1.4583,58600.0
55,-115.52,32.97,10.0,1879.0,387.0,1376.0,337.0,1.9911,67500.0
57,-115.52,32.73,17.0,1190.0,275.0,1113.0,258.0,2.3571,63100.0
59,-115.53,34.91,12.0,807.0,199.0,246.0,102.0,2.5391,40000.0
61,-115.53,32.97,35.0,1583.0,340.0,933.0,318.0,2.4063,70700.0
63,-115.53,32.73,14.0,1527.0,325.0,1453.0,332.0,1.7350,61200.0
65,-115.54,32.99,17.0,1697.0,268.0,911.0,254.0,4.3523,96000.0
67,-115.54,32.97,41.0,2429.0,454.0,1188.0,430.0,3.0091,70800.0
69,-115.55,32.98,33.0,2266.0,365.0,952.0,360.0,5.4349,143000.0
71,-115.55,32.82,34.0,1540.0,316.0,1013.0,274.0,2.5664,67500.0
73,-115.55,32.79,23.0,1004.0,221.0,697.0,201.0,1.6351,59600.0
75,-115.55,32.78,5.0,2652.0,606.0,1767.0,536.0,2.8025,84300.0
77,-115.56,32.80,28.0,1672.0,416.0,1335.0,397.0,1.5987,59400.0
79,-115.56,32.80,15.0,1171.0,328.0,1024.0,298.0,1.3882,69400.0
81,-115.56,32.79,18.0,1178.0,438.0,1377.0,429.0,1.3373,58300.0
83,-115.56,32.78,35.0,1185.0,202.0,615.0,191.0,4.6154,86200.0
85,-115.56,32.76,15.0,1278.0,217.0,653.0,185.0,4.4821,140300.0
87,-115.57,32.85,17.0,1039.0,256.0,728.0,246.0,1.7411,63500.0
89,-115.57,32.83,31.0,1494.0,289.0,959.0,284.0,3.5282,67500.0
91,-115.57,32.79,34.0,1152.0,208.0,621.0,208.0,3.6042,73600.0
93,-115.57,32.78,15.0,1413.0,279.0,803.0,277.0,4.3021,87500.0
95,-115.58,32.81,5.0,805.0,143.0,458.0,143.0,4.4750,96300.0
97,-115.58,32.79,14.0,1687.0,507.0,762.0,451.0,1.6635,64400.0
99,-115.59,32.85,20.0,1608.0,274.0,862.0,248.0,4.8750,90800.0

In [ ]:
#display even index position values of a particular column--->'total_bedroom'
df.loc[0:100:2,'total_bedrooms']
df['total_bedrooms'].loc[0:20:2]

0     1283.0
2      174.0
4      326.0
6      680.0
8     1175.0
10     801.0
12     248.0
14     378.0
16     322.0
18     386.0
20     360.0
Name: total_bedrooms, dtype: float64

In [ ]:
#display even index position of a specific column --->'total_bedroom','total_bedroom','population'
df[['total_rooms','total_bedrooms', 'population']].loc[0:20:2]
df.loc[0:20:2,['total_rooms','total_bedrooms', 'population']]

In [ ]:
#Applying the conditions for the columns
#print the even values of the column total_bedroom
df ['total_bedrooms']%2==0

In [ ]:
df.loc[df['total_bedrooms']%2==0]

In [ ]:
df_even = df[df['total_bedrooms']%2==0]['total_bedrooms']
df_even.head()

2    174.0
4    326.0
5    236.0
6    680.0
7    168.0
Name: total_bedrooms, dtype: float64

In [ ]:
#locate the rows in between
df.loc[[6500,2500,7000]]

In [ ]:
import numpy as np
a = np.array([10,12,13,15,16,18,17,21,22,26])
# print(a%2==0)
a_even = a[a%2==0]
print(a_even)

[10 12 16 18 22 26]

**Iloc**--> passes axis number of rows and columns

In [ ]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
#syntax--->df.iloc[row_index [start:end:step],column_index[start:end:step]]
#print the 1st 3 rows od following columns 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms'
df.iloc[0:3,1:5]
df.iloc[1,3]
df.iloc[3,6]

np.float64(226.0)

In [ ]:
df.iloc[0:100,1:5]

In [ ]:
#what is the differnce between the loc and iloc?
#loc support the filtering where as i loc doesnot suppprt filtering
#we can apply condtion in loc and we cannot apply condition in i loc.
df.iloc[df['total_bedroom'%2==0]]['total_bedroom']

In [ ]:
#locate the rows of specific columns, 'population', 'households','housing_median_age' [for ex:- locate first 10 rows].
df.loc[0:10,['population', 'households','housing_median_age']]

    population  households  housing_median_age
0       1015.0       472.0                15.0
1       1129.0       463.0                19.0
2        333.0       117.0                17.0
3        515.0       226.0                14.0
4        624.0       262.0                20.0
5        671.0       239.0                29.0
6       1841.0       633.0                25.0
7        375.0       158.0                41.0
8       3134.0      1056.0                34.0
9        787.0       271.0                46.0
10      2434.0       824.0                16.0

In [ ]:
#locate the rows of of indexes 545,789,543
df.loc[[545,789,543]]

In [ ]:
df.iloc[[545,789,543]]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
545,-117.01,32.81,26.0,4499.0,645.0,1866.0,626.0,5.5160,185100.0
789,-117.06,32.58,11.0,2879.0,679.0,2098.0,673.0,3.5125,142400.0
543,-117.01,32.84,23.0,1951.0,395.0,901.0,378.0,3.1023,143300.0

In [ ]:
#i want see the value at 676 index of total bedrooms
df.iloc[676,4]

np.float64(846.0)

In [ ]:
#find the unique values in the specific columns--->total_rooms
df['total_rooms'].unique()

array([5612., 7650.,  720., ..., 3810., 3003., 2694.])

In [ ]:
#find the frequency of each value in the specific column
df['housing_median_age'].value_counts()

housing_median_age
52.0    1052
36.0     715
35.0     692
16.0     635
17.0     576
34.0     567
33.0     513
26.0     503
18.0     478
25.0     461
32.0     458
37.0     437
15.0     416
19.0     412
28.0     400
27.0     397
24.0     389
31.0     384
30.0     384
20.0     383
23.0     382
29.0     374
21.0     373
14.0     347
22.0     323
38.0     318
42.0     308
39.0     302
44.0     296
43.0     286
13.0     249
40.0     249
45.0     235
41.0     232
10.0     226
11.0     208
5.0      199
46.0     196
12.0     192
8.0      178
47.0     175
9.0      172
4.0      161
7.0      151
48.0     135
6.0      129
50.0     112
49.0     111
2.0       49
3.0       46
51.0      32
1.0        2
Name: count, dtype: int64

In [ ]:
#find the duplicate data is present or not
df.duplicated().sum()

np.int64(0)

In [ ]:
#drop the duplicates
df.drop_duplicates(inplace=True)

In [ ]:
#access the single column--> df['column_name']
#access the multiple columns--> df[[col1,col2,col3...etc]]
#locate particular row of data---> df.loc[start:end:step]
#locate particular values from particular column---> df.iloc[row_index,col_index]
#find the unique values--->df['col_name'].unique()
#get the frequency of data points in specific column. df['col_name'].value_counts()
#find the duplicate in df---> df.duplicated().sum()
#drop the duplicate data-->df.drop_duplicates(inplace=True)

##04-06-2025##

In [ ]:
##Missing Dta ##

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series (["sam",np.nan,"Tim"])
print(s)

0    sam
1    NaN
2    Tim
dtype: object

In [ ]:
S.isnull()

0    False
1     True
2    False
dtype: bool

In [ ]:
S.notnull()

0     True
1    False
2     True
dtype: bool

In [ ]:
#how can we drop the null values
S.dropna()

0    sam
2    Tim
dtype: object

In [ ]:
from numpy import nan as NA

In [ ]:
df = pd.DataFrame([[1,2,3],[4,NA,5],[NA,NA,NA]])
print(df)

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

In [ ]:
#in above data frame drop the null values
df.dropna()

     0    1    2
0  1.0  2.0  3.0

In [ ]:
#delete only the row which is having all the null values
df.dropna(how = 'all')

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0

In [ ]:
df = pd.DataFrame([[1,2,3],[4,NA,5],[NA,NA,NA]])
print(df)

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

##05-06-2005##

##PIVOTING##

In [ ]:
#what is pivot table in pandas?
#A pivot table in pandas is a tool to summarize and analyze the data
import pandas as pd

In [ ]:
data = {
    'student': ['a','b','c','a','b','c'],
    'subject': ['maths','maths','maths','science','science','science'],
    'marks':[85,90,95,80,70,88],
    'sem':['sem1','sem1','sem1','sem2','sem2','sem2']
}
df = pd.DataFrame(data)
df

  student  subject  marks   sem
0       a    maths     85  sem1
1       b    maths     90  sem1
2       c    maths     95  sem1
3       a  science     80  sem2
4       b  science     70  sem2
5       c  science     88  sem2

In [ ]:
#synatx:- pd.pivot_table(data,values,index,columns,aggfunc)
pd.pivot_table(df,values='marks',index='student',columns='subject',aggfunc='mean')

subject  maths  science
student
a         85.0     80.0
b         90.0     70.0
c         95.0     88.0

In [ ]:
#add extra rows about student abc in above df
data2 = {
    'student' : ['a','b','c'],
    'subject':['maths','science','Histroy'],
    'marks':[82,91,90]}
df2 = pd.DataFrame(data2)
df = pd.concat([df,df2],ignore_index=True)
df

  student  subject  marks   sem
0       a    maths     85  sem1
1       b    maths     90  sem1
2       c    maths     95  sem1
3       a  science     80  sem2
4       b  science     70  sem2
5       c  science     88  sem2
6       a    maths     82   NaN
7       b  science     91   NaN
8       c  Histroy     90   NaN

In [ ]:
pd.pivot_table(df,values='marks',index='student',columns='subject',aggfunc='mean')

subject  Histroy  maths  science
student
a            NaN   83.5     80.0
b            NaN   90.0     80.5
c           90.0   95.0     88.0

In [ ]:
df2 = pd.read_csv('/content/sample_data/california_housing_train.csv')
df2.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
df2.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
#average of total_bed_rooms according to the latitude
pd.pivot_table(df2,values='total_bedrooms',index='latitude',aggfunc='mean')

          total_bedrooms
latitude
32.54         297.000000
32.55         935.000000
32.56         566.222222
32.57         499.615385
32.58         466.750000
...                  ...
41.82         284.000000
41.84         531.000000
41.86         687.333333
41.88         357.000000
41.95         501.000000

[840 rows x 1 columns]

In [ ]:
#df.append()
#df.loc[len(df)]=[]

In [ ]:
pd.pivot_table(df,values='marks',index='student',columns='subject',aggfunc='mean',fill_value= df['marks'].mean())

subject    Histroy  maths  science
student
a        85.666667   83.5     80.0
b        85.666667   90.0     80.5
c        90.000000   95.0     88.0

In [ ]:
#pd.pivot_table(data,values,index,columns,aggfunc,fiil_value)

**Group by Function**

In [ ]:
#group by function is applicable with aggregate functions
#min,max,sum,avg,count
#print the minimum marks of the students
df.groupby('student')['marks'].min()

student
a    80
b    70
c    88
Name: marks, dtype: int64

In [ ]:
#print total marks accordng to all sems
df.groupby('sem')['marks'].sum()

sem
sem1    270
sem2    238
Name: marks, dtype: int64

In [ ]:
pd.pivot_table(df,values='marks',index='sem',columns='student',aggfunc='sum')

student   a   b   c
sem
sem1     85  90  95
sem2     80  70  88

In [ ]:
#how to apply a function on the dataframe
def eligibility(num):
  if num >=75:
    print("eligible")
  else:
    print("not elgible")

In [ ]:
df['check']= df['marks'].apply(eligibility)

eligible
eligible
eligible
eligible
not elgible
eligible
eligible
eligible
eligible

In [ ]:
df['new']=df['marks'].apply(lambda a: a>75)

In [ ]:
def f1(n):
  print(n)
print(f1("saba"))

saba
None

In [ ]:
#timeseries data:- this data is in sequence of cronological order where we analyze the past data and we predict future
#There are 4 componets in the timeseries data
#1.trend component
#2.seasonality component
#3.cyclic component--(boom bust cycle)
#4.irregular component

In [ ]:
#how can we generate date range in pandas
#pd.date_range(start_date,periods,freq='d','h','min','s')
rng = pd.date _range('01/01/2025',periods=150,freq='s')
print(rng)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000